### ISSUE TITLE
 Requesting data from server?

### ISSUE THREAD

**Issue by b00f** [tihu-nlp/tihu-native#5]
Are you going to have a native android(?) app which gets data (audio) from a server? Good idea!

**Comment by shotor** [comment]
thanks :) yeah, that's the plan. the output will be two apps: android and ios. They're both built from one code base using react-native, which gives javascript bindings to native code. So hopefully I can write the whole thing in javascript. 

Only tricky part is calling the grpc server, which I might have to write a native module for.

**Comment by b00f** [comment]
Later we need to improve the performance of Tihu, which we can incerease it by simple changes in the code.
