### ISSUE TITLE
Parsing big text

### ISSUE THREAD

**Issue by b00f** [tihu-nlp/tihu-native#6]
Tihu is parsing text by sentences. When the first sentence finishes, it goes to the next. Look [here](https://github.com/tihu-nlp/tihu/blob/2ff73e19070526a032b8753aa25dc4f1cd459835/src/engine.cpp#L152)

Consider this in your further development. No need to think about it inside the native app.

**Comment by shotor** [comment]
might be good to limit the amount of text you can send to the grpc service for performance, or at least make it configurable.
